//! Golden tests against byte vectors produced by Pekko 1.1.3 itself.
//!
//! The hex strings below were generated by `jvm-test-node/src/main/java/rukko/testnode/GoldenDump.java`,
//! which uses Pekko's own `EnvelopeBuffer`/`HeaderBuilder` and `ArteryMessageSerializer`.
//! Regenerate with:
//!
//! ```text
//! cd jvm-test-node && mvn -q compile exec:java -Dexec.mainClass=rukko.testnode.GoldenDump
//! ```
//!
//! They pin down the parts of the wire format that Rukko must keep producing and accepting.

use bytes::Bytes;
use prost::Message as _;

use crate::protocol::{ActorPath, FrameHeader, InternalMessage, Message, MessageEnvelope, UniqueAddress};

// ---- Vectors from GoldenDump (Pekko 1.1.3) ---------------------------------------------------

/// sender = pekko://RukkoIT@127.0.0.1:4242/temp/_user_echo$a, recipient = pekko://PekkoNode@127.0.0.1:25552/user/echo,
/// uid = 42, serializer = 20, manifest = "", payload = "Hello Artery!"
const USER_STRING_ENVELOPE: &str = "000000002a00000000000000140000001c0000004e0000007b000000300070656b6b6f3a2f2f52756b6b6f4954403132372e302e302e313a343234322f74656d702f5f757365725f6563686f24612b0070656b6b6f3a2f2f50656b6b6f4e6f6465403132372e302e302e313a32353535322f757365722f6563686f000048656c6c6f2041727465727921";

/// Same as above but with `setNoSender()` (deadLetters): Pekko writes an empty sender literal.
const USER_STRING_NO_SENDER_ENVELOPE: &str = "000000002a00000000000000140000001c0000001e0000004b00000000002b0070656b6b6f3a2f2f50656b6b6f4e6f6465403132372e302e302e313a32353535322f757365722f6563686f000048656c6c6f2041727465727921";

/// HandshakeReq(from = RukkoIT@127.0.0.1:4242 uid 42, to = PekkoNode@127.0.0.1:25552), serializer 17, manifest "d"
const HANDSHAKE_REQ_PAYLOAD: &str = "0a220a1e0a0570656b6b6f120752756b6b6f49541a093132372e302e302e31209221102a12210a0570656b6b6f120950656b6b6f4e6f64651a093132372e302e302e3120d0c701";
/// HandshakeRsp(from = PekkoNode@127.0.0.1:25552 uid 7), manifest "e"
const HANDSHAKE_RSP_PAYLOAD: &str = "0a250a210a0570656b6b6f120950656b6b6f4e6f64651a093132372e302e302e3120d0c7011007";
/// ActorSystemTerminating(from = RukkoIT@127.0.0.1:4242 uid 42), manifest "b"
const ACTOR_SYSTEM_TERMINATING_PAYLOAD: &str = "0a220a1e0a0570656b6b6f120752756b6b6f49541a093132372e302e302e31209221102a";
/// ActorSystemTerminatingAck(from = PekkoNode@127.0.0.1:25552 uid 7), manifest "c"
const ACTOR_SYSTEM_TERMINATING_ACK_PAYLOAD: &str = "0a250a210a0570656b6b6f120950656b6b6f4e6f64651a093132372e302e302e3120d0c7011007";

/// A complete HandshakeReq envelope as Pekko frames it: no sender, no recipient, manifest "d", uid 42.
const HANDSHAKE_REQ_ENVELOPE: &str = "000000002a00000000000000110000001c0000001e00000020000000000000000100640a220a1e0a0570656b6b6f120752756b6b6f49541a093132372e302e302e31209221102a12210a0570656b6b6f120950656b6b6f4e6f64651a093132372e302e302e3120d0c701";

/// uid = Long.MIN_VALUE, serializer = -1, manifest = "longlonglongliteralmanifest", empty payload
const EDGE_ENVELOPE: &str = "000000000000000000000080ffffffff1c0000004e0000007b000000300070656b6b6f3a2f2f52756b6b6f4954403132372e302e302e313a343234322f74656d702f5f757365725f6563686f24612b0070656b6b6f3a2f2f50656b6b6f4e6f6465403132372e302e302e313a32353535322f757365722f6563686f1b006c6f6e676c6f6e676c6f6e676c69746572616c6d616e6966657374";

const SENDER: &str = "pekko://RukkoIT@127.0.0.1:4242/temp/_user_echo$a";
const RECIPIENT: &str = "pekko://PekkoNode@127.0.0.1:25552/user/echo";

// ---- Helpers --------------------------------------------------------------------------------

fn hex(s: &str) -> Bytes {
    assert!(s.len().is_multiple_of(2), "odd hex length");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex"))
        .collect::<Vec<u8>>()
        .into()
}

fn rukko_addr() -> UniqueAddress {
    UniqueAddress {
        address: ActorPath::new("RukkoIT".into(), "127.0.0.1".into(), 4242, "system".into()),
        uid: 42,
    }
}

fn pekko_addr() -> UniqueAddress {
    UniqueAddress {
        address: ActorPath::new("PekkoNode".into(), "127.0.0.1".into(), 25552, "system".into()),
        uid: 7,
    }
}

fn le_u32(b: &[u8], off: usize) -> u32 {
    u32::from_le_bytes([b[off], b[off + 1], b[off + 2], b[off + 3]])
}

// ---- Envelope header: decoding what Pekko sends ------------------------------------------------

#[test]
fn decodes_user_string_envelope_from_pekko() {
    let mut buf = hex(USER_STRING_ENVELOPE);
    let env = MessageEnvelope::decode(&mut buf).expect("Pekko envelope must decode");

    assert_eq!(env.version, 0);
    assert_eq!(env.flags, 0);
    assert_eq!(env.actor_ref_compression_version, 0);
    assert_eq!(env.class_manifest_compression_version, 0);
    assert_eq!(env.uid, 42);
    assert_eq!(env.serializer_id, 20);
    assert_eq!(env.sender.to_string(), SENDER);
    assert_eq!(env.recipient.to_string(), RECIPIENT);
    assert_eq!(env.class_manifest, "");
    assert_eq!(env.message_payload.as_ref(), b"Hello Artery!");
}

#[test]
fn decodes_edge_case_envelope_from_pekko() {
    // Long.MIN_VALUE and serializer -1 are written as two's complement by the JVM
    let mut buf = hex(EDGE_ENVELOPE);
    let env = MessageEnvelope::decode(&mut buf).expect("edge envelope must decode");

    assert_eq!(env.uid, i64::MIN as u64);
    assert_eq!(env.serializer_id, u32::MAX);
    assert_eq!(env.sender.to_string(), SENDER);
    assert_eq!(env.recipient.to_string(), RECIPIENT);
    assert_eq!(env.class_manifest, "longlonglongliteralmanifest");
    assert!(env.message_payload.is_empty());
}

#[test]
fn pekko_literal_tags_are_offsets_into_the_literal_section() {
    // Documents the actual Pekko layout: a literal tag holds the absolute offset of its
    // length-prefixed literal. The high byte (TagTypeMask 0xFF000000) is zero for literals and
    // non-zero for compression-table indices.
    let b = hex(USER_STRING_ENVELOPE);
    let sender_tag = le_u32(&b, 16);
    let recipient_tag = le_u32(&b, 20);
    let manifest_tag = le_u32(&b, 24);

    assert_eq!(sender_tag, 28, "sender literal starts right after the fixed header");
    assert_eq!(recipient_tag, 28 + 2 + SENDER.len() as u32);
    assert_eq!(manifest_tag, recipient_tag + 2 + RECIPIENT.len() as u32);
    for tag in [sender_tag, recipient_tag, manifest_tag] {
        assert_eq!(tag & 0xFF00_0000, 0, "literal tags never carry the compression type mask");
    }
}

/// Known gap: Pekko encodes "no sender" (deadLetters) as an empty literal, which Rukko's
/// decoder currently rejects because `ActorPath::from_string("")` fails. A JVM actor that
/// replies with `tell(msg, ActorRef.noSender())` therefore never reaches the asker.
#[test]
#[ignore = "known gap: empty sender literal (deadLetters) is rejected by MessageEnvelope::decode"]
fn decodes_envelope_without_sender_from_pekko() {
    let mut buf = hex(USER_STRING_NO_SENDER_ENVELOPE);
    let env = MessageEnvelope::decode(&mut buf).expect("envelope with empty sender literal must decode");
    assert_eq!(env.recipient.to_string(), RECIPIENT);
    assert_eq!(env.message_payload.as_ref(), b"Hello Artery!");
}

#[test]
fn envelope_without_sender_currently_fails_to_decode() {
    // Pin the current behaviour so that fixing the gap above shows up as a test change.
    let mut buf = hex(USER_STRING_NO_SENDER_ENVELOPE);
    assert!(MessageEnvelope::decode(&mut buf).is_err());
}

// ---- Envelope header: what Rukko sends compared with Pekko ------------------------------------

#[test]
fn encodes_user_string_envelope_identically_to_pekko_except_literal_tags() {
    let sender = ActorPath::from_string(SENDER.to_string()).unwrap();
    let recipient = ActorPath::from_string(RECIPIENT.to_string()).unwrap();
    let mut env = MessageEnvelope::new(
        sender,
        recipient,
        InternalMessage::from_user_message(&Message::text("Hello Artery!")),
    )
    .unwrap();
    env.uid = 42;

    let ours = env.encode().unwrap();
    let theirs = hex(USER_STRING_ENVELOPE);

    assert_eq!(ours.len(), theirs.len(), "frame length must match");
    assert_eq!(&ours[..16], &theirs[..16], "version/flags/table versions/uid/serializer");
    assert_eq!(&ours[28..], &theirs[28..], "literal section and payload");

    // Rukko writes 0 in all three literal tags; Pekko writes the literal offsets.
    // Pekko's parser only checks the type mask, so both are accepted, but this is a deviation.
    assert_eq!(&ours[16..28], &[0u8; 12]);
    assert_ne!(&ours[16..28], &theirs[16..28]);
}

// ---- Control message payloads (ArteryMessageSerializer, id 17) --------------------------------

#[test]
fn handshake_req_payload_matches_pekko() {
    let msg = InternalMessage::handshake_req(rukko_addr(), pekko_addr().address);
    assert_eq!(msg.serializer_id, 17);
    assert_eq!(msg.encode().unwrap(), hex(HANDSHAKE_REQ_PAYLOAD));
}

#[test]
fn handshake_rsp_payload_matches_pekko() {
    let msg = InternalMessage::handshake_rsp(pekko_addr());
    assert_eq!(msg.serializer_id, 17);
    assert_eq!(msg.encode().unwrap(), hex(HANDSHAKE_RSP_PAYLOAD));
}

#[test]
fn actor_system_terminating_payload_matches_pekko() {
    let msg = InternalMessage::actor_system_terminating(rukko_addr());
    assert_eq!(msg.encode().unwrap(), hex(ACTOR_SYSTEM_TERMINATING_PAYLOAD));
}

#[test]
fn actor_system_terminating_ack_payload_matches_pekko() {
    let msg = InternalMessage::actor_system_terminating_ack(pekko_addr());
    assert_eq!(msg.encode().unwrap(), hex(ACTOR_SYSTEM_TERMINATING_ACK_PAYLOAD));
}

#[test]
fn control_manifests_match_pekko() {
    let manifest = |m: InternalMessage| {
        MessageEnvelope::new(rukko_addr().address, pekko_addr().address, m)
            .unwrap()
            .class_manifest
    };
    assert_eq!(manifest(InternalMessage::handshake_req(rukko_addr(), pekko_addr().address)), "d");
    assert_eq!(manifest(InternalMessage::handshake_rsp(pekko_addr())), "e");
    assert_eq!(manifest(InternalMessage::actor_system_terminating(rukko_addr())), "b");
    assert_eq!(manifest(InternalMessage::actor_system_terminating_ack(pekko_addr())), "c");
    assert_eq!(
        manifest(InternalMessage::from_user_message(&Message::text("x"))),
        "",
        "primitive-string messages have an empty manifest"
    );
}

#[test]
fn pekko_handshake_rsp_payload_decodes_as_message_with_address() {
    let rsp = crate::pekko_protobuf::MessageWithAddress::decode(hex(HANDSHAKE_RSP_PAYLOAD).as_ref()).unwrap();
    assert_eq!(rsp.address.uid, 7);
    assert_eq!(rsp.address.address.protocol, "pekko");
    assert_eq!(rsp.address.address.system, "PekkoNode");
    assert_eq!(rsp.address.address.hostname, "127.0.0.1");
    assert_eq!(rsp.address.address.port, 25552);
}

#[test]
fn pekko_handshake_req_envelope_has_empty_refs_and_manifest_d() {
    // Pekko frames control messages with NO sender and NO recipient literal (both length 0).
    // Rukko's full decoder cannot represent that (see decodes_envelope_without_sender_from_pekko),
    // which is why transport.rs has a separate header-only parser for control frames.
    let b = hex(HANDSHAKE_REQ_ENVELOPE);
    assert_eq!(b[0], 0, "version");
    assert_eq!(le_u32(&b, 12), 17, "serializer");
    assert_eq!(&b[28..30], &[0, 0], "empty sender literal");
    assert_eq!(&b[30..32], &[0, 0], "empty recipient literal");
    assert_eq!(&b[32..34], &[1, 0], "manifest length 1");
    assert_eq!(b[34], b'd');
    assert_eq!(&b[35..], hex(HANDSHAKE_REQ_PAYLOAD).as_ref(), "payload follows the literals");

    let mut buf = b.clone();
    assert!(MessageEnvelope::decode(&mut buf).is_err(), "full decoder rejects empty refs today");
}

// ---- TCP framing (TcpFraming.scala) -----------------------------------------------------------

#[test]
fn frame_header_is_four_byte_little_endian_length() {
    // TcpFraming.encodeFrameHeader(frameLength)
    assert_eq!(FrameHeader::new(5).encode().as_ref(), &[0x05, 0, 0, 0]);
    assert_eq!(FrameHeader::new(0x0102_0304).encode().as_ref(), &[0x04, 0x03, 0x02, 0x01]);
    let mut buf = Bytes::from_static(&[0x2a, 0, 0, 0, 0xff]);
    assert_eq!(FrameHeader::decode(&mut buf).unwrap().size, 42);
    assert_eq!(buf.as_ref(), &[0xff], "decode consumes exactly four bytes");
}

#[test]
fn connection_header_is_magic_plus_stream_id() {
    // TcpFraming.encodeConnectionHeader(streamId) = "AKKA" ++ streamId.toByte
    use crate::protocol::StreamId;
    assert_eq!(StreamId::Control as u8, 1);
    assert_eq!(StreamId::Ordinary as u8, 2);
    assert_eq!(StreamId::Large as u8, 3);
    let header = [b'A', b'K', b'K', b'A', StreamId::Control as u8];
    assert_eq!(&header, b"AKKA\x01");
}
